version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: shiroha-postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=a1436381036
      - POSTGRES_DB=shiroha
    ports:
      - "5431:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
    restart: always