baseUrl: "http://localhost:8080"
adminRealm: "master"
clientRealm: "shiroha.love"
admin:
  adminClientID: "shiroha-management"
  adminClientSecret: "ofFJvfoSnCDJCYI14x1k1ziFLdWn58aZ"
  adminUsername: "shiroha-admin"
  adminPassword: "a1436381036"
client:
  clientID: "gin_client"
  clientSecret: "DszRqPSkGOcpBVRPnSrluomopwKn7zKM"
